kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
    description: Defines how to deploy the database server
  name: mssql
  labels:
    {{- include "netcandystore.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    name: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotation:
        {{- toYaml . | nindent 8 }}
      labels:
        {{- include "netcandystore.selectorLabels" . | nindent 8 }}
        name: mssql
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
        - name: tempdir
          emptyDir: {}
      initContainers:
        - name: csv-downloader
          image: 'registry.access.redhat.com/ubi8/ubi:latest'
          command:
            - /bin/bash
            - '-c'
            - |
              url=${URLPREFIX}
              csvfiles=(StatusCodes.csv ProductCategories.csv Products.csv)
              echo "Downloading CSV files"
              echo "====================="
              for csvfile in ${csvfiles[@]}
              do
                curl ${url}/${csvfile} --output /tmp/${csvfile}
                chmod 777 /tmp/${csvfile}
              done
          env:
            - name: URLPREFIX
              value: 'https://raw.githubusercontent.com/DonSchenck/NetCandyStore/main'
          resources: {}
          volumeMounts:
            - name: tempdir
              mountPath: /tmp
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      containers:
      - name: mssql
        image: {{ .Values.netcandy.dbimage }}
        ports:
        - containerPort: 1433
        env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: MSSQL_PID
            value: Developer
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: SA_PASSWORD
          - name: MSSQL_SERVICE
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: SERVICE_NAME
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        - name: tempdir
          mountPath: /tmp
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 31433
      targetPort: 1433
  type: LoadBalancer
