kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mssql
  namespace: netcandystore
  labels:
    {{- include "netcandystore.labels" . | nindent 4 }}
  annotations:
    description: Defines how to deploy the database server
    meta.helm.sh/release-name: ncs
    meta.helm.sh/release-namespace: netcandystore
spec:
  replicas: 1
  selector:
    name: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      name: mssql
      labels:
        name: mssql
        app.kubernetes.io/instance: ncs
        app.kubernetes.io/name: netcandystore
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: csv-downloader
        image: 'registry.access.redhat.com/ubi8/ubi:latest'
        command:
          - /bin/bash
          - '-c'
          - |
            url=${URLPREFIX}
            csvfiles=(StatusCodes.csv ProductCategories.csv Products.csv)
            echo "Downloading CSV files"
            echo "====================="
            for csvfile in ${csvfiles[@]}
            do
              curl ${url}/${csvfile} --output /tmp/${csvfile}
              chmod 777 /tmp/${csvfile}
            done
        env:
        - name: URLPREFIX
          value: 'https://raw.githubusercontent.com/DonSchenck/NetCandyStore/main'
        resources: {}
        volumeMounts:
        - name: tempdir
          mountPath: /tmp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/rhel/server:2019-CU1-rhel-8
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: 'Y'
        - name: MSSQL_PID
          value: Developer
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD
        - name: MSSQL_SERVICE
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SERVICE_NAME
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql
        - name: tempdir
          mountPath: /tmp
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: mssql-pvc
      - name: tempdir
        emptyDir: {}
